# Generated by Django 3.1.2 on 2020-11-21 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eclipse', '0002_auto_20201120_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
