# Generated by Django 3.1.2 on 2020-12-09 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20201208_0831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='java',
            options={'verbose_name_plural': 'Java'},
        ),
    ]
