# Generated by Django 3.1.2 on 2020-12-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20201209_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='java',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
